
/* Auth */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHECK_USER_STATUS_REQUEST = 'CHECK_USER_STATUS_REQUEST';
export const CHECK_USER_STATUS_SUCCESS = 'CHECK_USER_STATUS_SUCCESS';
export const CHECK_USER_STATUS_FAIL = 'CHECK_USER_STATUS_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

/* Notifications */
export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR_HIDE';

/* Desk Actions */
export const UPLOAD_FILES_REQUEST = 'UPLOAD_FILES_REQUEST';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL';
export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const GET_MORE_ALBUMS_REQUEST = 'GET_MORE_ALBUMS_REQUEST';
export const GET_MORE_ALBUMS_SUCCESS = 'GET_MORE_ALBUMS_SUCCESS';
export const GET_MORE_ALBUMS_FAIL = 'GET_MORE_ALBUMS_FAIL';
export const GET_ALBUM_PHOTOS_REQUEST = 'GET_ALBUM_PHOTOS_REQUEST';
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCCESS';
export const GET_ALBUM_PHOTOS_FAIL = 'GET_ALBUM_PHOTOS_FAIL';
export const GET_PHOTO_REQUEST = 'GET_PHOTO_REQUEST';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';
export const GET_PHOTO_FAIL = 'GET_PHOTO_FAIL';
export const GET_MORE_PHOTOS_REQUEST = 'GET_MORE_PHOTOS_REQUEST';
export const GET_MORE_PHOTOS_SUCCESS = 'GET_MORE_PHOTOS_SUCCESS';
export const GET_MORE_PHOTOS_FAIL = 'GET_MORE_PHOTOS_FAIL';
